version: '3'
services:
  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  worka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/worka
    command: >
      sh -c "python manage.py makemigrations accounts &&
             python manage.py migrate accounts &&
             python manage.py makemigrations question &&
             python manage.py migrate question &&
             python manage.py makemigrations post &&
             python manage.py migrate post &&
             python manage.py migrate &&
             python manage.py loaddata accounts/mbti.json &&
             gunicorn worka.wsgi:application --bind 0.0.0.0:8000 --workers 3"
