version: '3'
services:
  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  worka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/worka
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 --workers 3 worka.wsgi:application -e DJANGO_SETTINGS_MODULE=worka.settings.prod"
