version: '3'
services:
  worka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py makemigrations accounts &&
             python manage.py migrate accounts &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=worka
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
