# Generated by Django 3.0.7 on 2020-06-11 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2020, 6, 11, 14, 54, 32, 909961, tzinfo=utc)
            ),
        ),
    ]
